export const LOAD_EMPLOYEE = "LOAD_EMPLOYEE";
export const LOAD_EMPLOYEE_SUCCESS = "LOAD_EMPLOYEE_SUCCESS";
export const LOAD_EMPLOYEE_FAILURE = "LOAD_EMPLOYEE_FAILURE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAILURE = "UPDATE_EMPLOYEE_FAILURE";
export const CLEAR_EMPLOYEE = "CLEAR_EMPLOYEE";
