export const LOAD_DEPARTMENT = "LOAD_DEPARTMENT";
export const LOAD_DEPARTMENT_SUCCESS = "LOAD_DEPARTMENT_SUCCESS";
export const LOAD_DEPARTMENT_FAILURE = "LOAD_DEPARTMENT_FAILURE";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_FAILURE = "UPDATE_DEPARTMENT_FAILURE";
